// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    IAppLocale: typeof import('~icons/app/locale')['default']
    IEmojiBear: typeof import('~icons/fluent-emoji-flat/bear')['default']
    IEmojiChicken: typeof import('~icons/fluent-emoji-flat/chicken')['default']
    IEpBellFilled: typeof import('~icons/ep/bell-filled')['default']
    IEpConnection: typeof import('~icons/ep/connection')['default']
    IEpFullScreen: typeof import('~icons/ep/full-screen')['default']
    IEpLock: typeof import('~icons/ep/lock')['default']
    IEpMoon: typeof import('~icons/ep/moon')['default']
    IEpOdometer: typeof import('~icons/ep/odometer')['default']
    IEpOperation: typeof import('~icons/ep/operation')['default']
    IEpSetting: typeof import('~icons/ep/setting')['default']
    IEpSunny: typeof import('~icons/ep/sunny')['default']
    IEpSwitchButton: typeof import('~icons/ep/switch-button')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    IFluentEmojiFlatBear: typeof import('~icons/fluent-emoji-flat/bear')['default']
    IRiFullscreenExitFill: typeof import('~icons/ri/fullscreen-exit-fill')['default']
    IRiFullscreenFill: typeof import('~icons/ri/fullscreen-fill')['default']
    IRiMoonFill: typeof import('~icons/ri/moon-fill')['default']
    IRiSunFill: typeof import('~icons/ri/sun-fill')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitch: typeof import('./../src/components/ThemeSwitch/index.vue')['default']
  }
}
