// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    IAppLocale: typeof import('~icons/app/locale')['default']
    IAppLogo: typeof import('~icons/app/logo')['default']
    IEmojiChicken: typeof import('~icons/fluent-emoji-flat/chicken')['default']
    IEpArrowLeftBold: typeof import('~icons/ep/arrow-left-bold')['default']
    IEpBellFilled: typeof import('~icons/ep/bell-filled')['default']
    IEpExpand: typeof import('~icons/ep/expand')['default']
    IEpFold: typeof import('~icons/ep/fold')['default']
    IEpLock: typeof import('~icons/ep/lock')['default']
    IEpMenu: typeof import('~icons/ep/menu')['default']
    IEpSwitchButton: typeof import('~icons/ep/switch-button')['default']
    IEpTools: typeof import('~icons/ep/tools')['default']
    IEpUserFilled: typeof import('~icons/ep/user-filled')['default']
    IRiAdminFill: typeof import('~icons/ri/admin-fill')['default']
    IRiAppsFill: typeof import('~icons/ri/apps-fill')['default']
    IRiFullscreenExitFill: typeof import('~icons/ri/fullscreen-exit-fill')['default']
    IRiFullscreenFill: typeof import('~icons/ri/fullscreen-fill')['default']
    IRiMoonFill: typeof import('~icons/ri/moon-fill')['default']
    IRiSunFill: typeof import('~icons/ri/sun-fill')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitch: typeof import('./../src/components/ThemeSwitch/index.vue')['default']
  }
}
